name: Deploy docs

on:
  push:
    paths:
      - docusaurus/**/*
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install & build
        run: |
          cd docusaurus
          npm ci
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_DIR: docusaurus/build
          PUBLISH_BRANCH: gh-pages
